services:
  - type: web
    name: personal-website
    plan: free
    runtime: node
    region: frankfurt
    repo: https://github.com/osdiab/personal-website.git
    buildCommand: pnpm install --filter "@osdiab-website/web..."; pnpm run --filter "@osdiab-website/web" build
    startCommand: pnpm run --filter "@osdiab-website/web" start
    healthCheckPath: /api/health
    domains:
      - next.omardiab.com
      - next2.omardiab.com
  - type: web
    name: personal-website-hasura
    region: frankfurt
    plan: free
    runtime: docker
    dockerfilePath: ./apps/gql-engine/Dockerfile
    dockerContext: ./apps/gql-engine
    healthCheckPath: /healthz
    envVars:
      - key: HASURA_GRAPHQL_DATABASE_URL
        fromDatabase:
          name: personal-website-main
          property: connectionString
      - key: HASURA_ENABLE_CONSOLE
        value: true

databases:
  - name: personal-website-main
    region: frankfurt
    databaseName: omardiab
    plan: free
    user: web
