services:
  - type: web
    name: web
    plan: starter
    runtime: node
    region: frankfurt
    repo: https://github.com/osdiab/personal-website.git
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 60
      targetCPUPercent: 60
    buildCommand: pnpm install --filter "@osdiab-website/web..."; pnpm run --filter "@osdiab-website/web" build
    startCommand: pnpm run --filter "@osdiab-website/web" start
    healthCheckPath: /api/health
    domains:
      - next.omardiab.com
      - next2.omardiab.com
  - type: web
    name: hasura
    region: frankfurt
    plan: starter
    runtime: image
    image:
      url: docker.io/hasura/graphql-engine:v2.27.0
    envVars:
      - key: HASURA_GRAPHQL_DATABASE_URL
        fromDatabase:
          name: main
          property: connectionString

databases:
  - name: main
    region: frankfurt
    databaseName: omardiab
    user: web
