services:
  - &web-service
    type: web
    name: personal-website--prd
    plan: free
    runtime: node
    region: frankfurt
    branch: prd
    buildCommand: pnpm install --filter "@osdiab-website/web..."; pnpm run --filter "@osdiab-website/web" build
    startCommand: pnpm run --filter "@osdiab-website/web" start
    healthCheckPath: /api/health
    envVars:
      - key: HASURA_GRAPHQL_HOST
        fromService:
          type: web
          name: personal-website-gql-engine--prd
          property: host
      - key: HASURA_GRAPHQL_PORT
        fromService:
          type: web
          name: personal-website-gql-engine--prd
          property: port
    domains:
      - next.omardiab.com
      - next2.omardiab.com
  - &gql-engine-service
    type: web
    name: personal-website-gql-engine--prd
    region: frankfurt
    plan: free
    runtime: docker
    branch: prd
    dockerfilePath: ./apps/gql-engine/Dockerfile
    dockerContext: ./apps/gql-engine
    healthCheckPath: /healthz
    envVars:
      - key: HASURA_GRAPHQL_DATABASE_URL
        fromDatabase:
          name: personal-website-main--prd
          property: connectionString
      - key: HASURA_ENABLE_CONSOLE
        value: true
  ## staging versions of these
  - <<: *web-service
    name: personal-website--stg
    branch: main
    envVars:
      - key: HASURA_GRAPHQL_HOST_PORT
        fromService:
          type: web
          name: personal-website-gql-engine--stg
          property: hostport
    domains:
      - staging.next.omardiab.com
      - staging.next2.omardiab.com
  - <<: *gql-engine-service
    name: personal-website-gql-engine--stg
    branch: main
    envVars:
      - key: HASURA_GRAPHQL_DATABASE_URL
        fromDatabase:
          name: personal-website-main--stg
          property: connectionString
      - key: HASURA_ENABLE_CONSOLE
        value: true

databases:
  - name: personal-website-main--prd
    region: frankfurt
    databaseName: omardiab
    plan: starter
    user: web
  - name: personal-website-main--stg
    region: frankfurt
    databaseName: omardiab
    plan: free
    user: web
