services:
  - type: web
    name: web
    plan: starter
    runtime: node
    repo: https://github.com/osdiab/personal-website.git
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 60
      targetCPUPercent: 60
    buildCommand: pnpm install --filter "@osdiab-website/web"; pnpm run --filter "@osdiab-website/web" build
    startCommand: pnpm run --filter "@osdiab-website/web" start
    healthCheckPath: /api/health
    domains:
      - next.omardiab.com
      - next2.omardiab.com
