version: '3.6'
services:
  postgres:
    image: postgres:15
    # https://github.com/hasura/graphql-engine/issues/3672
    command: postgres -c jit=off
    ports:
      - "8001:5432" # different external port number
    restart: always
    volumes:
    - uhr-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8081:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      # env vars without values are provided by environment
      DOPPLER_TOKEN:
volumes:
  uhr-db-data:

