version: '3.6'
services:
  postgres:
    image: postgres:15
    # https://github.com/hasura/graphql-engine/issues/3672
    command: postgres -c jit=off
    ports:
      - "8001:5432" # different external port number
    restart: always
    volumes:
    - uhr-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8081:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      # env vars without values are provided by environment
      HASURA_GRAPHQL_DATABASE_URL:
      HASURA_GRAPHQL_ENABLE_CONSOLE:
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      HASURA_GRAPHQL_ADMIN_SECRET:
volumes:
  uhr-db-data:

