name: Checks
on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: true
      pnpm-version:
        type: string
        required: true

jobs:
  check-web-types:
    name: Check Web Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ inputs.pnpm-version }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --filter "web-app..."
      - name: Check Web App Types
        run: pnpm run --filter "web-app" typecheck

  check-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ inputs.pnpm-version }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --filter "monorepo..."
      - name: Run Lint
        run: pnpm lint

  check-format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ inputs.pnpm-version }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --filter monorepo
      - name: Run Format
        run: pnpm format:check
