name: Deploy
on:
  push:
    branches:
      - stg
      - prd
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - stg

concurrency:
  group: ${{ github.workflow }}-${{github.event_name}}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  get-tool-versions:
    name: Get Tool Versions
    runs-on: ubuntu-latest
    outputs:
      pnpm: ${{ steps.versions.outputs.pnpm }}
      nodejs: ${{ steps.versions.outputs.nodejs }}
    steps:
      - uses: actions/checkout@v3
      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions

  run-checks:
    name: Run Code Checks
    uses: "./.github/workflows/checks.yml"
    needs: [get-tool-versions]
    with:
      node-version: ${{needs.get-tool-versions.outputs.nodejs}}
      pnpm-version: ${{needs.get-tool-versions.outputs.pnpm}}

