name: Clean Up Preview Deploy
on:
  pull_request_target:
    types: [closed]
    branches:
      - stg

jobs:
  delete-existing-neon-branch:
    name: "Delete old Neon postgres branch"
    uses: "./.github/workflows/delete-neon-pr-branch.yml"
    with:
      pr-number: ${{github.event.number}}
    secrets:
      neon-project-id: ${{secrets.NEON_PROJECT_ID_APP_DB_STG}}
      neon-api-key: ${{secrets.NEON_API_KEY}}

  delete-hasura-preview-app:
    name: Delete Hasura preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: osdiab/hasura-cloud-preview-apps@main
        with:
          name: "personal-website-pr-${{github.event.number}}"
          delete: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HASURA_CLOUD_ACCESS_TOKEN: ${{secrets.HASURA_CLOUD_ACCESS_TOKEN}}
