name: Clean Up Preview Deploy
on:
  pull_request_target:
    types: [closed]
    branches:
      - stg

jobs:
  delete-existing-neon-branch:
    name: "Delete old Neon postgres branch"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/delete-neon-pr-branch
        with:
          pr-number: ${{github.event.number}}

  delete-hasura-preview-app:
    name: Delete Hasura preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: osdiab/hasura-cloud-preview-apps@main
        with:
          name: "personal-website-pr-${{github.event.number}}"
          delete: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HASURA_CLOUD_ACCESS_TOKEN: ${{secrets.HASURA_CLOUD_ACCESS_TOKEN}}
