name: Deploy
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  get-tool-versions:
    name: Get Tool Versions
    runs-on: ubuntu-latest
    outputs:
      pnpm: ${{ steps.versions.outputs.pnpm }}
      nodejs: ${{ steps.versions.outputs.nodejs }}
    steps:
      - uses: actions/checkout@v3
      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions

  check-web-types:
    name: Check Web Types
    runs-on: ubuntu-latest
    needs: [get-tool-versions]
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ needs.get-tool-versions.outputs.pnpm }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.get-tool-versions.outputs.nodejs }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --filter "@osdiab-website/web..."
      - name: Check Web App Types
        run: pnpm run --filter @osdiab-website/app typecheck

  check-lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [get-tool-versions]
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ needs.get-tool-versions.outputs.pnpm }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.get-tool-versions.outputs.nodejs }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --filter "@osdiab-website/monorepo..."
      - name: Run Lint
        run: pnpm lint

  check-format:
    name: Check format
    runs-on: ubuntu-latest
    needs: [get-tool-versions]
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ needs.get-tool-versions.outputs.pnpm }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.get-tool-versions.outputs.nodejs }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --filter "@osdiab-website/monorepo"
      - name: Run Format
        run: pnpm format:check

  build-web-app:
    name: Build Web App
    runs-on: ubuntu-latest
    needs: [get-tool-versions]
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ needs.get-tool-versions.outputs.pnpm }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.get-tool-versions.outputs.nodejs }}
          cache: "pnpm"
      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v2
      - name: Install dependencies
        run: pnpm install --filter "@osdiab-website/web..."
      - name: Pull Vercel config
        run: pnpx vercel pull --yes --token=${VERCEL_TOKEN}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEB_APP }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Preview Build
        run: pnpx vercel build
        if: github.event_name == 'pull_request_target'
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEB_APP }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_WEB_APP_STG }}
      - name: Production Build
        run: pnpx vercel build --prod
        if: github.event_name == 'push'
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEB_APP }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_WEB_APP_PRD }}
      - name: Tar build artifact for deployment
        run: tar -cf vercel-build.tar ./.vercel
      - uses: actions/upload-artifact@v3
        with:
          name: build-web-app-${{ github.sha }}
          path: vercel-build.tar

  deploy-to-vercel:
    permissions:
      pull-requests: write
      contents: write
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs:
      [
        get-tool-versions,
        check-web-types,
        check-lint,
        check-format,
        build-web-app,
      ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-web-app-${{ github.sha }}
      - name: Extract tar build artifact for deployment
        run: tar -xf vercel-build.tar
      - name: Deploy Vercel Preview
        uses: amondnet/vercel-action@v20
        if: github.event_name == 'pull_request_target'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_WEB_APP }}
          vercel-args: --prebuilt
          # alias-domains: |
          #   pr-{{PR_NUMBER}}.next-vercel.omardiab.com
      - name: Deploy Vercel Production
        uses: amondnet/vercel-action@v25
        if: github.event_name == 'push'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_WEB_APP }}
          vercel-args: --prebuilt --prod
