name: Deploy
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  deploy-to-vercel:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --filter "@osdiab-website/web..." --filter "@osdiab-website/monorepo"
      - name: Pull Vercel config
        run: pnpm vercel pull --yes --token=${VERCEL_TOKEN}
        working-directory: example/nextjs
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEB_APP }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Preview Build
        run: pnpm vercel build
        if: github.ref != 'refs/head/main'
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEB_APP }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      - name: Production Build
        run: pnpm vercel build --prod
        if: github.ref == 'refs/head/main'
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEB_APP }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      - name: Deploy Vercel
        uses: amondnet/vercel-action@v20
        if: github.event_name == 'pull_request_target'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_WEB_APP }}
          vercel-args: --prebuilt
          working-directory: example/nextjs
          alias-domains: |
            pr-{{PR_NUMBER}}.next-vercel.omardiab.com
